package:
  stage: build
  image: kramos/alpine-zip:latest
  script:
    - zip pvv.zip manifest.json main.js jquery-3.3.1.min.js jquery-ui.js jquery-ui.css popup.html icon.png resizable_white.png
  artifacts:
    paths:
      - pvv.zip
  variables:
    GIT_SSL_NO_VERIFY: "true"
